version: 1.0.0
services:
  - php:
      version: 7.1

events:
  build:
    steps:
      - composer:
          type: script
          script:
            # Run composer install to setup the project and modules.
            - composer install --no-progress --no-interaction --no-dev
      - node_v7.10:
          type: script
          script:
            - nvm install v7.10
            - nvm use 7.10
      - example_theme:
          type: script
          script:
            - pushd docroot/themes/custom/example_theme
            - npm install
            - npm run build
            - rm -fr node_modules
            - popd
      - example_preact_app:
          type: script
          script:
            - pushd docroot/modules/custom/example_preact/components/example_preact_app
            - npm install
            - npm run build
            - popd
