version: 1.0.0
services:
  - php:
      version: 7.1

events:
  build:
    steps:
      - composer:
          type: script
          script:
            # Run composer install to setup the project and modules.
            - composer install --no-progress
